Issue #10 gestion vehicules
2019-d05-code/gestion-des-transports-back pull request #1
Opened 2019-05-22 11:52 UTC by ElenHayot

2019-05-22 12:03 UTC, demeeuus submitted a review, later dismissed

2019-05-22 12:28 UTC, eric-pennecot requested changes
Il me semble qu'il faudrait mettre la Categorie du Vehicule dans une enum indépendante (fichier à part), et la renommer de manière plus spécifique (par exemple CategorieV ou CategorieVehicule, car "Categorie" pourrait représenter n'importe quoi, tel des salariés). Ca ne génèrera pas de table indépendante tant qu'il n'y a pas d'annotation Entity. Puis passer le champ en private dans le Vehicule, avec getter et setter.

2019-05-23 07:24 UTC, ElenHayot commented
Ok, je fais de suite une enumération à part, effectivement, je pense que ce sera plus ergonomique

2019-05-23 08:30 UTC, eric-pennecot submitted a review, later dismissed

2019-05-23 08:50 UTC, demeeuus requested changes

2019-05-23 08:50 UTC, DarceWorld13 commented on src/main/java/dev/security/WebSecurityConfig.java
> +                .antMatchers(HttpMethod.POST, "/admin/vehicules").permitAll()
il me semble qu'il faut soumettre à authentification le post

2019-05-23 09:07 UTC, ElenHayot commented on src/main/java/dev/security/WebSecurityConfig.java
> +                .antMatchers(HttpMethod.POST, "/admin/vehicules").permitAll()
est-ce qu'on ne le ferait pas à la fin? Lorsque l'authentification fonctionnera? Ou fonctionne-t-elle déjà?

2019-05-23 09:35 UTC, rmy17 approved these changes

2019-05-23 09:41 UTC, demeeuus approved these changes

2019-05-23 09:52 UTC, eric-pennecot approved these changes

2019-05-23 09:53 UTC, merged